# Generated by Django 4.2.4 on 2023-10-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frirends',
        ),
    ]
