# Generated by Django 4.2.4 on 2023-10-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_pic_friend_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='./static/user.png', null=True, upload_to='img'),
        ),
    ]
