# Generated by Django 4.2.4 on 2023-10-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_bio_profile_followers_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='my_followers', to='home.friend'),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
