# Generated by Django 4.2.4 on 2023-10-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
