# Generated by Django 4.2.4 on 2023-10-22 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_friend_request_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
