# Generated by Django 4.2.4 on 2023-10-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_profile_followers_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='created',
        ),
    ]
