# Generated by Django 4.2.4 on 2023-10-22 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_chatmessages_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
