# Generated by Django 4.2.4 on 2023-10-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_chatmessages_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
