# Generated by Django 4.2.4 on 2023-10-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
